# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import uesynth_pb2 as uesynth__pb2


class UESynthServiceStub(object):
  """Service definition for UESynth
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ControlStream = channel.stream_stream(
        '/uesynth.UESynthService/ControlStream',
        request_serializer=uesynth__pb2.ActionRequest.SerializeToString,
        response_deserializer=uesynth__pb2.FrameResponse.FromString,
        )
    self.SetCameraTransform = channel.unary_unary(
        '/uesynth.UESynthService/SetCameraTransform',
        request_serializer=uesynth__pb2.SetCameraTransformRequest.SerializeToString,
        response_deserializer=uesynth__pb2.CommandResponse.FromString,
        )
    self.GetCameraTransform = channel.unary_unary(
        '/uesynth.UESynthService/GetCameraTransform',
        request_serializer=uesynth__pb2.GetCameraTransformRequest.SerializeToString,
        response_deserializer=uesynth__pb2.GetCameraTransformResponse.FromString,
        )
    self.CaptureRgbImage = channel.unary_unary(
        '/uesynth.UESynthService/CaptureRgbImage',
        request_serializer=uesynth__pb2.CaptureRequest.SerializeToString,
        response_deserializer=uesynth__pb2.ImageResponse.FromString,
        )
    self.CaptureDepthMap = channel.unary_unary(
        '/uesynth.UESynthService/CaptureDepthMap',
        request_serializer=uesynth__pb2.CaptureRequest.SerializeToString,
        response_deserializer=uesynth__pb2.ImageResponse.FromString,
        )
    self.CaptureSegmentationMask = channel.unary_unary(
        '/uesynth.UESynthService/CaptureSegmentationMask',
        request_serializer=uesynth__pb2.CaptureRequest.SerializeToString,
        response_deserializer=uesynth__pb2.ImageResponse.FromString,
        )
    self.SetObjectTransform = channel.unary_unary(
        '/uesynth.UESynthService/SetObjectTransform',
        request_serializer=uesynth__pb2.SetObjectTransformRequest.SerializeToString,
        response_deserializer=uesynth__pb2.CommandResponse.FromString,
        )
    self.GetObjectTransform = channel.unary_unary(
        '/uesynth.UESynthService/GetObjectTransform',
        request_serializer=uesynth__pb2.GetObjectTransformRequest.SerializeToString,
        response_deserializer=uesynth__pb2.GetObjectTransformResponse.FromString,
        )
    self.CreateCamera = channel.unary_unary(
        '/uesynth.UESynthService/CreateCamera',
        request_serializer=uesynth__pb2.CreateCameraRequest.SerializeToString,
        response_deserializer=uesynth__pb2.CommandResponse.FromString,
        )
    self.DestroyCamera = channel.unary_unary(
        '/uesynth.UESynthService/DestroyCamera',
        request_serializer=uesynth__pb2.DestroyCameraRequest.SerializeToString,
        response_deserializer=uesynth__pb2.CommandResponse.FromString,
        )
    self.SetResolution = channel.unary_unary(
        '/uesynth.UESynthService/SetResolution',
        request_serializer=uesynth__pb2.SetResolutionRequest.SerializeToString,
        response_deserializer=uesynth__pb2.CommandResponse.FromString,
        )
    self.CaptureNormals = channel.unary_unary(
        '/uesynth.UESynthService/CaptureNormals',
        request_serializer=uesynth__pb2.CaptureRequest.SerializeToString,
        response_deserializer=uesynth__pb2.ImageResponse.FromString,
        )
    self.CaptureOpticalFlow = channel.unary_unary(
        '/uesynth.UESynthService/CaptureOpticalFlow',
        request_serializer=uesynth__pb2.CaptureRequest.SerializeToString,
        response_deserializer=uesynth__pb2.ImageResponse.FromString,
        )
    self.SpawnObject = channel.unary_unary(
        '/uesynth.UESynthService/SpawnObject',
        request_serializer=uesynth__pb2.SpawnObjectRequest.SerializeToString,
        response_deserializer=uesynth__pb2.CommandResponse.FromString,
        )
    self.DestroyObject = channel.unary_unary(
        '/uesynth.UESynthService/DestroyObject',
        request_serializer=uesynth__pb2.DestroyObjectRequest.SerializeToString,
        response_deserializer=uesynth__pb2.CommandResponse.FromString,
        )
    self.SetMaterial = channel.unary_unary(
        '/uesynth.UESynthService/SetMaterial',
        request_serializer=uesynth__pb2.SetMaterialRequest.SerializeToString,
        response_deserializer=uesynth__pb2.CommandResponse.FromString,
        )
    self.ListObjects = channel.unary_unary(
        '/uesynth.UESynthService/ListObjects',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=uesynth__pb2.ListObjectsResponse.FromString,
        )
    self.SetLighting = channel.unary_unary(
        '/uesynth.UESynthService/SetLighting',
        request_serializer=uesynth__pb2.SetLightingRequest.SerializeToString,
        response_deserializer=uesynth__pb2.CommandResponse.FromString,
        )


class UESynthServiceServicer(object):
  """Service definition for UESynth
  """

  def ControlStream(self, request_iterator, context):
    """New bidirectional streaming method
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetCameraTransform(self, request, context):
    """Camera and Viewport Control
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCameraTransform(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CaptureRgbImage(self, request, context):
    """Data Capture
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CaptureDepthMap(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CaptureSegmentationMask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetObjectTransform(self, request, context):
    """Object Manipulation
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetObjectTransform(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateCamera(self, request, context):
    """Additional Camera Control
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DestroyCamera(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetResolution(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CaptureNormals(self, request, context):
    """Additional Data Capture
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CaptureOpticalFlow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SpawnObject(self, request, context):
    """Additional Object Manipulation
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DestroyObject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetMaterial(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListObjects(self, request, context):
    """Scene Control
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetLighting(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UESynthServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ControlStream': grpc.stream_stream_rpc_method_handler(
          servicer.ControlStream,
          request_deserializer=uesynth__pb2.ActionRequest.FromString,
          response_serializer=uesynth__pb2.FrameResponse.SerializeToString,
      ),
      'SetCameraTransform': grpc.unary_unary_rpc_method_handler(
          servicer.SetCameraTransform,
          request_deserializer=uesynth__pb2.SetCameraTransformRequest.FromString,
          response_serializer=uesynth__pb2.CommandResponse.SerializeToString,
      ),
      'GetCameraTransform': grpc.unary_unary_rpc_method_handler(
          servicer.GetCameraTransform,
          request_deserializer=uesynth__pb2.GetCameraTransformRequest.FromString,
          response_serializer=uesynth__pb2.GetCameraTransformResponse.SerializeToString,
      ),
      'CaptureRgbImage': grpc.unary_unary_rpc_method_handler(
          servicer.CaptureRgbImage,
          request_deserializer=uesynth__pb2.CaptureRequest.FromString,
          response_serializer=uesynth__pb2.ImageResponse.SerializeToString,
      ),
      'CaptureDepthMap': grpc.unary_unary_rpc_method_handler(
          servicer.CaptureDepthMap,
          request_deserializer=uesynth__pb2.CaptureRequest.FromString,
          response_serializer=uesynth__pb2.ImageResponse.SerializeToString,
      ),
      'CaptureSegmentationMask': grpc.unary_unary_rpc_method_handler(
          servicer.CaptureSegmentationMask,
          request_deserializer=uesynth__pb2.CaptureRequest.FromString,
          response_serializer=uesynth__pb2.ImageResponse.SerializeToString,
      ),
      'SetObjectTransform': grpc.unary_unary_rpc_method_handler(
          servicer.SetObjectTransform,
          request_deserializer=uesynth__pb2.SetObjectTransformRequest.FromString,
          response_serializer=uesynth__pb2.CommandResponse.SerializeToString,
      ),
      'GetObjectTransform': grpc.unary_unary_rpc_method_handler(
          servicer.GetObjectTransform,
          request_deserializer=uesynth__pb2.GetObjectTransformRequest.FromString,
          response_serializer=uesynth__pb2.GetObjectTransformResponse.SerializeToString,
      ),
      'CreateCamera': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCamera,
          request_deserializer=uesynth__pb2.CreateCameraRequest.FromString,
          response_serializer=uesynth__pb2.CommandResponse.SerializeToString,
      ),
      'DestroyCamera': grpc.unary_unary_rpc_method_handler(
          servicer.DestroyCamera,
          request_deserializer=uesynth__pb2.DestroyCameraRequest.FromString,
          response_serializer=uesynth__pb2.CommandResponse.SerializeToString,
      ),
      'SetResolution': grpc.unary_unary_rpc_method_handler(
          servicer.SetResolution,
          request_deserializer=uesynth__pb2.SetResolutionRequest.FromString,
          response_serializer=uesynth__pb2.CommandResponse.SerializeToString,
      ),
      'CaptureNormals': grpc.unary_unary_rpc_method_handler(
          servicer.CaptureNormals,
          request_deserializer=uesynth__pb2.CaptureRequest.FromString,
          response_serializer=uesynth__pb2.ImageResponse.SerializeToString,
      ),
      'CaptureOpticalFlow': grpc.unary_unary_rpc_method_handler(
          servicer.CaptureOpticalFlow,
          request_deserializer=uesynth__pb2.CaptureRequest.FromString,
          response_serializer=uesynth__pb2.ImageResponse.SerializeToString,
      ),
      'SpawnObject': grpc.unary_unary_rpc_method_handler(
          servicer.SpawnObject,
          request_deserializer=uesynth__pb2.SpawnObjectRequest.FromString,
          response_serializer=uesynth__pb2.CommandResponse.SerializeToString,
      ),
      'DestroyObject': grpc.unary_unary_rpc_method_handler(
          servicer.DestroyObject,
          request_deserializer=uesynth__pb2.DestroyObjectRequest.FromString,
          response_serializer=uesynth__pb2.CommandResponse.SerializeToString,
      ),
      'SetMaterial': grpc.unary_unary_rpc_method_handler(
          servicer.SetMaterial,
          request_deserializer=uesynth__pb2.SetMaterialRequest.FromString,
          response_serializer=uesynth__pb2.CommandResponse.SerializeToString,
      ),
      'ListObjects': grpc.unary_unary_rpc_method_handler(
          servicer.ListObjects,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=uesynth__pb2.ListObjectsResponse.SerializeToString,
      ),
      'SetLighting': grpc.unary_unary_rpc_method_handler(
          servicer.SetLighting,
          request_deserializer=uesynth__pb2.SetLightingRequest.FromString,
          response_serializer=uesynth__pb2.CommandResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'uesynth.UESynthService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
