//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "CoreMinimal.h"
#include "Kismet/BlueprintAsyncActionBase.h"
#include "TurboLinkGrpcClient.h"
#include "UesynthMessage.h"
#include "UesynthNode.generated.h"

class UUESynthService;
class UUESynthServiceClient;

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceSetCameraTransform : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceSetCameraTransformDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService SetCameraTransform",
		AdvancedDisplay = 2))
	static UCallUESynthServiceSetCameraTransform* SetCameraTransform(UObject* WorldContextObject, const FGrpcUesynthSetCameraTransformRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceSetCameraTransformDelegate OnSetCameraTransformResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceSetCameraTransformDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthSetCameraTransformRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceGetCameraTransform : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceGetCameraTransformDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthGetCameraTransformResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService GetCameraTransform",
		AdvancedDisplay = 2))
	static UCallUESynthServiceGetCameraTransform* GetCameraTransform(UObject* WorldContextObject, const FGrpcUesynthGetCameraTransformRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceGetCameraTransformDelegate OnGetCameraTransformResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceGetCameraTransformDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthGetCameraTransformRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthGetCameraTransformResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceCaptureRgbImage : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceCaptureRgbImageDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthImageResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService CaptureRgbImage",
		AdvancedDisplay = 2))
	static UCallUESynthServiceCaptureRgbImage* CaptureRgbImage(UObject* WorldContextObject, const FGrpcUesynthCaptureRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceCaptureRgbImageDelegate OnCaptureRgbImageResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceCaptureRgbImageDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthCaptureRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceCaptureDepthMap : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceCaptureDepthMapDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthImageResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService CaptureDepthMap",
		AdvancedDisplay = 2))
	static UCallUESynthServiceCaptureDepthMap* CaptureDepthMap(UObject* WorldContextObject, const FGrpcUesynthCaptureRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceCaptureDepthMapDelegate OnCaptureDepthMapResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceCaptureDepthMapDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthCaptureRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceCaptureSegmentationMask : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceCaptureSegmentationMaskDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthImageResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService CaptureSegmentationMask",
		AdvancedDisplay = 2))
	static UCallUESynthServiceCaptureSegmentationMask* CaptureSegmentationMask(UObject* WorldContextObject, const FGrpcUesynthCaptureRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceCaptureSegmentationMaskDelegate OnCaptureSegmentationMaskResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceCaptureSegmentationMaskDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthCaptureRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceSetObjectTransform : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceSetObjectTransformDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService SetObjectTransform",
		AdvancedDisplay = 2))
	static UCallUESynthServiceSetObjectTransform* SetObjectTransform(UObject* WorldContextObject, const FGrpcUesynthSetObjectTransformRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceSetObjectTransformDelegate OnSetObjectTransformResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceSetObjectTransformDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthSetObjectTransformRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceGetObjectTransform : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceGetObjectTransformDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthGetObjectTransformResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService GetObjectTransform",
		AdvancedDisplay = 2))
	static UCallUESynthServiceGetObjectTransform* GetObjectTransform(UObject* WorldContextObject, const FGrpcUesynthGetObjectTransformRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceGetObjectTransformDelegate OnGetObjectTransformResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceGetObjectTransformDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthGetObjectTransformRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthGetObjectTransformResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceCreateCamera : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceCreateCameraDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService CreateCamera",
		AdvancedDisplay = 2))
	static UCallUESynthServiceCreateCamera* CreateCamera(UObject* WorldContextObject, const FGrpcUesynthCreateCameraRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceCreateCameraDelegate OnCreateCameraResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceCreateCameraDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthCreateCameraRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceDestroyCamera : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceDestroyCameraDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService DestroyCamera",
		AdvancedDisplay = 2))
	static UCallUESynthServiceDestroyCamera* DestroyCamera(UObject* WorldContextObject, const FGrpcUesynthDestroyCameraRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceDestroyCameraDelegate OnDestroyCameraResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceDestroyCameraDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthDestroyCameraRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceSetResolution : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceSetResolutionDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService SetResolution",
		AdvancedDisplay = 2))
	static UCallUESynthServiceSetResolution* SetResolution(UObject* WorldContextObject, const FGrpcUesynthSetResolutionRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceSetResolutionDelegate OnSetResolutionResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceSetResolutionDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthSetResolutionRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceCaptureNormals : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceCaptureNormalsDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthImageResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService CaptureNormals",
		AdvancedDisplay = 2))
	static UCallUESynthServiceCaptureNormals* CaptureNormals(UObject* WorldContextObject, const FGrpcUesynthCaptureRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceCaptureNormalsDelegate OnCaptureNormalsResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceCaptureNormalsDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthCaptureRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceCaptureOpticalFlow : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceCaptureOpticalFlowDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthImageResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService CaptureOpticalFlow",
		AdvancedDisplay = 2))
	static UCallUESynthServiceCaptureOpticalFlow* CaptureOpticalFlow(UObject* WorldContextObject, const FGrpcUesynthCaptureRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceCaptureOpticalFlowDelegate OnCaptureOpticalFlowResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceCaptureOpticalFlowDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthCaptureRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceSpawnObject : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceSpawnObjectDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService SpawnObject",
		AdvancedDisplay = 2))
	static UCallUESynthServiceSpawnObject* SpawnObject(UObject* WorldContextObject, const FGrpcUesynthSpawnObjectRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceSpawnObjectDelegate OnSpawnObjectResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceSpawnObjectDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthSpawnObjectRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceDestroyObject : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceDestroyObjectDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService DestroyObject",
		AdvancedDisplay = 2))
	static UCallUESynthServiceDestroyObject* DestroyObject(UObject* WorldContextObject, const FGrpcUesynthDestroyObjectRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceDestroyObjectDelegate OnDestroyObjectResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceDestroyObjectDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthDestroyObjectRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceSetMaterial : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceSetMaterialDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService SetMaterial",
		AdvancedDisplay = 2))
	static UCallUESynthServiceSetMaterial* SetMaterial(UObject* WorldContextObject, const FGrpcUesynthSetMaterialRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceSetMaterialDelegate OnSetMaterialResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceSetMaterialDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthSetMaterialRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceListObjects : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceListObjectsDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthListObjectsResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService ListObjects",
		AdvancedDisplay = 2))
	static UCallUESynthServiceListObjects* ListObjects(UObject* WorldContextObject, const FGrpcGoogleProtobufEmpty& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceListObjectsDelegate OnListObjectsResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceListObjectsDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcGoogleProtobufEmpty Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthListObjectsResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallUESynthServiceSetLighting : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FUESynthServiceSetLightingDelegate, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|UESynthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call UESynthService SetLighting",
		AdvancedDisplay = 2))
	static UCallUESynthServiceSetLighting* SetLighting(UObject* WorldContextObject, const FGrpcUesynthSetLightingRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceSetLightingDelegate OnSetLightingResponse;

	UPROPERTY(BlueprintAssignable)
	FUESynthServiceSetLightingDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UUESynthService* UESynthService;
	
	UPROPERTY()
	UUESynthServiceClient* UESynthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcUesynthSetLightingRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);

	void Shutdown();
};
