//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "SGoogleProtobuf/EmptyMessage.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "UesynthMessage.generated.h"

UENUM(BlueprintType, meta = (DisplayName="Uesynth.ActionRequest.Action", ScriptName="EGrpcUesynthActionRequestAction"))
enum class EGrpcUesynthActionRequestAction : uint8
{
    SetCameraTransform=0,
    GetCameraTransform=1,
    CaptureRgb=2,
    CaptureDepth=3,
    CaptureSegmentation=4,
    CaptureNormals=5,
    CaptureOpticalFlow=6,
    SetObjectTransform=7,
    GetObjectTransform=8,
    CreateCamera=9,
    DestroyCamera=10,
    SetResolution=11,
    SpawnObject=12,
    DestroyObject=13,
    SetMaterial=14,
    ListObjects=15,
    SetLighting=16,
};

UENUM(BlueprintType, meta = (DisplayName="Uesynth.FrameResponse.Response", ScriptName="EGrpcUesynthFrameResponseResponse"))
enum class EGrpcUesynthFrameResponseResponse : uint8
{
    CommandResponse=0,
    CameraTransform=1,
    ImageResponse=2,
    ObjectTransform=3,
    ObjectsList=4,
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.ActionRequest.Action",
    HasNativeMake = "TurboLinkGrpc.GrpcUesynthActionRequestActionHelperLibrary.MakeAction",
    HasNativeBreak = "TurboLinkGrpc.GrpcUesynthActionRequestActionHelperLibrary.BreakAction"))
struct FGrpcUesynthActionRequestAction : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcUesynthActionRequestAction ActionCase;

    TSharedPtr<FGrpcUesynthSetCameraTransformRequest> SetCameraTransform;

    TSharedPtr<FGrpcUesynthGetCameraTransformRequest> GetCameraTransform;

    TSharedPtr<FGrpcUesynthCaptureRequest> CaptureRgb;

    TSharedPtr<FGrpcUesynthCaptureRequest> CaptureDepth;

    TSharedPtr<FGrpcUesynthCaptureRequest> CaptureSegmentation;

    TSharedPtr<FGrpcUesynthCaptureRequest> CaptureNormals;

    TSharedPtr<FGrpcUesynthCaptureRequest> CaptureOpticalFlow;

    TSharedPtr<FGrpcUesynthSetObjectTransformRequest> SetObjectTransform;

    TSharedPtr<FGrpcUesynthGetObjectTransformRequest> GetObjectTransform;

    TSharedPtr<FGrpcUesynthCreateCameraRequest> CreateCamera;

    TSharedPtr<FGrpcUesynthDestroyCameraRequest> DestroyCamera;

    TSharedPtr<FGrpcUesynthSetResolutionRequest> SetResolution;

    TSharedPtr<FGrpcUesynthSpawnObjectRequest> SpawnObject;

    TSharedPtr<FGrpcUesynthDestroyObjectRequest> DestroyObject;

    TSharedPtr<FGrpcUesynthSetMaterialRequest> SetMaterial;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcGoogleProtobufEmpty ListObjects;

    TSharedPtr<FGrpcUesynthSetLightingRequest> SetLighting;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.ActionRequest"))
struct FGrpcUesynthActionRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RequestId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthActionRequestAction Action;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.FrameResponse.Response",
    HasNativeMake = "TurboLinkGrpc.GrpcUesynthFrameResponseResponseHelperLibrary.MakeResponse",
    HasNativeBreak = "TurboLinkGrpc.GrpcUesynthFrameResponseResponseHelperLibrary.BreakResponse"))
struct FGrpcUesynthFrameResponseResponse : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcUesynthFrameResponseResponse ResponseCase;

    TSharedPtr<FGrpcUesynthCommandResponse> CommandResponse;

    TSharedPtr<FGrpcUesynthGetCameraTransformResponse> CameraTransform;

    TSharedPtr<FGrpcUesynthImageResponse> ImageResponse;

    TSharedPtr<FGrpcUesynthGetObjectTransformResponse> ObjectTransform;

    TSharedPtr<FGrpcUesynthListObjectsResponse> ObjectsList;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.FrameResponse"))
struct FGrpcUesynthFrameResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RequestId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthFrameResponseResponse Response;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.Vector3"))
struct FGrpcUesynthVector3 : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float X = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Y = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Z = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.Rotator"))
struct FGrpcUesynthRotator : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Pitch = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Yaw = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Roll = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.Transform"))
struct FGrpcUesynthTransform : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthVector3 Location;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthRotator Rotation;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthVector3 Scale;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.CommandResponse"))
struct FGrpcUesynthCommandResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Success = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Message = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.SetCameraTransformRequest"))
struct FGrpcUesynthSetCameraTransformRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString CameraName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthTransform Transform;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.GetCameraTransformRequest"))
struct FGrpcUesynthGetCameraTransformRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString CameraName = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.GetCameraTransformResponse"))
struct FGrpcUesynthGetCameraTransformResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthTransform Transform;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Success = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Message = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.CaptureRequest"))
struct FGrpcUesynthCaptureRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString CameraName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt32 Width = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt32 Height = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.ImageResponse"))
struct FGrpcUesynthImageResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FBytes ImageData;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt32 Width = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt32 Height = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Format = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.SetObjectTransformRequest"))
struct FGrpcUesynthSetObjectTransformRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ObjectName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthTransform Transform;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.GetObjectTransformRequest"))
struct FGrpcUesynthGetObjectTransformRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ObjectName = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.GetObjectTransformResponse"))
struct FGrpcUesynthGetObjectTransformResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthTransform Transform;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Success = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Message = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.CreateCameraRequest"))
struct FGrpcUesynthCreateCameraRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString CameraName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthTransform InitialTransform;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.DestroyCameraRequest"))
struct FGrpcUesynthDestroyCameraRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString CameraName = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.SetResolutionRequest"))
struct FGrpcUesynthSetResolutionRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString CameraName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt32 Width = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FUInt32 Height = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.ListObjectsResponse"))
struct FGrpcUesynthListObjectsResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FString> ObjectNames;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.SpawnObjectRequest"))
struct FGrpcUesynthSpawnObjectRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ObjectName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString AssetPath = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthTransform InitialTransform;
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.DestroyObjectRequest"))
struct FGrpcUesynthDestroyObjectRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ObjectName = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.SetMaterialRequest"))
struct FGrpcUesynthSetMaterialRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ObjectName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString MaterialProperty = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Value = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Uesynth.SetLightingRequest"))
struct FGrpcUesynthSetLightingRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString LightName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Intensity = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthVector3 Color;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcUesynthTransform Transform;
};

UCLASS()
class UGrpcUesynthActionRequestActionHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Uesynth", meta=(BlueprintThreadSafe))
    static FGrpcUesynthActionRequestAction MakeAction(EGrpcUesynthActionRequestAction ActionCase, 
        FGrpcUesynthSetCameraTransformRequest SetCameraTransform, FGrpcUesynthGetCameraTransformRequest GetCameraTransform, FGrpcUesynthCaptureRequest CaptureRgb, 
        FGrpcUesynthCaptureRequest CaptureDepth, FGrpcUesynthCaptureRequest CaptureSegmentation, FGrpcUesynthCaptureRequest CaptureNormals, 
        FGrpcUesynthCaptureRequest CaptureOpticalFlow, FGrpcUesynthSetObjectTransformRequest SetObjectTransform, FGrpcUesynthGetObjectTransformRequest GetObjectTransform, 
        FGrpcUesynthCreateCameraRequest CreateCamera, FGrpcUesynthDestroyCameraRequest DestroyCamera, FGrpcUesynthSetResolutionRequest SetResolution, 
        FGrpcUesynthSpawnObjectRequest SpawnObject, FGrpcUesynthDestroyObjectRequest DestroyObject, FGrpcUesynthSetMaterialRequest SetMaterial, 
        FGrpcGoogleProtobufEmpty ListObjects, FGrpcUesynthSetLightingRequest SetLighting 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Uesynth", meta=(BlueprintThreadSafe))
    static void BreakAction(const FGrpcUesynthActionRequestAction& Action, EGrpcUesynthActionRequestAction& ActionCase, 
        FGrpcUesynthSetCameraTransformRequest& SetCameraTransform, FGrpcUesynthGetCameraTransformRequest& GetCameraTransform, FGrpcUesynthCaptureRequest& CaptureRgb, 
        FGrpcUesynthCaptureRequest& CaptureDepth, FGrpcUesynthCaptureRequest& CaptureSegmentation, FGrpcUesynthCaptureRequest& CaptureNormals, 
        FGrpcUesynthCaptureRequest& CaptureOpticalFlow, FGrpcUesynthSetObjectTransformRequest& SetObjectTransform, FGrpcUesynthGetObjectTransformRequest& GetObjectTransform, 
        FGrpcUesynthCreateCameraRequest& CreateCamera, FGrpcUesynthDestroyCameraRequest& DestroyCamera, FGrpcUesynthSetResolutionRequest& SetResolution, 
        FGrpcUesynthSpawnObjectRequest& SpawnObject, FGrpcUesynthDestroyObjectRequest& DestroyObject, FGrpcUesynthSetMaterialRequest& SetMaterial, 
        FGrpcGoogleProtobufEmpty& ListObjects, FGrpcUesynthSetLightingRequest& SetLighting 
    );
};

UCLASS()
class UGrpcUesynthFrameResponseResponseHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Uesynth", meta=(BlueprintThreadSafe))
    static FGrpcUesynthFrameResponseResponse MakeResponse(EGrpcUesynthFrameResponseResponse ResponseCase, 
        FGrpcUesynthCommandResponse CommandResponse, FGrpcUesynthGetCameraTransformResponse CameraTransform, FGrpcUesynthImageResponse ImageResponse, 
        FGrpcUesynthGetObjectTransformResponse ObjectTransform, FGrpcUesynthListObjectsResponse ObjectsList 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Uesynth", meta=(BlueprintThreadSafe))
    static void BreakResponse(const FGrpcUesynthFrameResponseResponse& Response, EGrpcUesynthFrameResponseResponse& ResponseCase, 
        FGrpcUesynthCommandResponse& CommandResponse, FGrpcUesynthGetCameraTransformResponse& CameraTransform, FGrpcUesynthImageResponse& ImageResponse, 
        FGrpcUesynthGetObjectTransformResponse& ObjectTransform, FGrpcUesynthListObjectsResponse& ObjectsList 
    );
};
