//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SUesynth/UesynthMessage.h"
#include "UesynthClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnUESynthServiceControlStreamWriteComplete, FGrpcContextHandle, Handle);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceControlStreamResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthFrameResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceSetCameraTransformResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceGetCameraTransformResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthGetCameraTransformResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceCaptureRgbImageResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthImageResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceCaptureDepthMapResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthImageResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceCaptureSegmentationMaskResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthImageResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceSetObjectTransformResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceGetObjectTransformResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthGetObjectTransformResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceCreateCameraResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceDestroyCameraResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceSetResolutionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceCaptureNormalsResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthImageResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceCaptureOpticalFlowResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthImageResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceSpawnObjectResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceDestroyObjectResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceSetMaterialResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceListObjectsResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthListObjectsResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnUESynthServiceSetLightingResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcUesynthCommandResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UUESynthServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceControlStreamWriteComplete OnControlStreamWriteComplete;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceControlStreamResponse OnControlStreamResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceSetCameraTransformResponse OnSetCameraTransformResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceGetCameraTransformResponse OnGetCameraTransformResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceCaptureRgbImageResponse OnCaptureRgbImageResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceCaptureDepthMapResponse OnCaptureDepthMapResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceCaptureSegmentationMaskResponse OnCaptureSegmentationMaskResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceSetObjectTransformResponse OnSetObjectTransformResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceGetObjectTransformResponse OnGetObjectTransformResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceCreateCameraResponse OnCreateCameraResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceDestroyCameraResponse OnDestroyCameraResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceSetResolutionResponse OnSetResolutionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceCaptureNormalsResponse OnCaptureNormalsResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceCaptureOpticalFlowResponse OnCaptureOpticalFlowResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceSpawnObjectResponse OnSpawnObjectResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceDestroyObjectResponse OnDestroyObjectResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceSetMaterialResponse OnSetMaterialResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceListObjectsResponse OnListObjectsResponse;

	UPROPERTY(BlueprintAssignable)
	FOnUESynthServiceSetLightingResponse OnSetLightingResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitControlStream();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void ControlStream(FGrpcContextHandle Handle, const FGrpcUesynthActionRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitSetCameraTransform();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void SetCameraTransform(FGrpcContextHandle Handle, const FGrpcUesynthSetCameraTransformRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetCameraTransform();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void GetCameraTransform(FGrpcContextHandle Handle, const FGrpcUesynthGetCameraTransformRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCaptureRgbImage();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void CaptureRgbImage(FGrpcContextHandle Handle, const FGrpcUesynthCaptureRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCaptureDepthMap();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void CaptureDepthMap(FGrpcContextHandle Handle, const FGrpcUesynthCaptureRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCaptureSegmentationMask();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void CaptureSegmentationMask(FGrpcContextHandle Handle, const FGrpcUesynthCaptureRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitSetObjectTransform();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void SetObjectTransform(FGrpcContextHandle Handle, const FGrpcUesynthSetObjectTransformRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetObjectTransform();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void GetObjectTransform(FGrpcContextHandle Handle, const FGrpcUesynthGetObjectTransformRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCreateCamera();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void CreateCamera(FGrpcContextHandle Handle, const FGrpcUesynthCreateCameraRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitDestroyCamera();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void DestroyCamera(FGrpcContextHandle Handle, const FGrpcUesynthDestroyCameraRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitSetResolution();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void SetResolution(FGrpcContextHandle Handle, const FGrpcUesynthSetResolutionRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCaptureNormals();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void CaptureNormals(FGrpcContextHandle Handle, const FGrpcUesynthCaptureRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCaptureOpticalFlow();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void CaptureOpticalFlow(FGrpcContextHandle Handle, const FGrpcUesynthCaptureRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitSpawnObject();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void SpawnObject(FGrpcContextHandle Handle, const FGrpcUesynthSpawnObjectRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitDestroyObject();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void DestroyObject(FGrpcContextHandle Handle, const FGrpcUesynthDestroyObjectRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitSetMaterial();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void SetMaterial(FGrpcContextHandle Handle, const FGrpcUesynthSetMaterialRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitListObjects();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void ListObjects(FGrpcContextHandle Handle, const FGrpcGoogleProtobufEmpty& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitSetLighting();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void SetLighting(FGrpcContextHandle Handle, const FGrpcUesynthSetLightingRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

