//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SUesynth/UesynthService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "uesynth.grpc.pb.h"
#include "UesynthService_Private.generated.h"

class UUESynthService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::uesynth::UESynthService::Stub> Stub;
};


UCLASS()
class UUESynthServiceSetCameraTransformLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FSetCameraTransformResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceGetCameraTransformLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthGetCameraTransformResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FGetCameraTransformResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceCaptureRgbImageLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FCaptureRgbImageResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceCaptureDepthMapLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FCaptureDepthMapResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceCaptureSegmentationMaskLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FCaptureSegmentationMaskResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceSetObjectTransformLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FSetObjectTransformResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceGetObjectTransformLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthGetObjectTransformResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FGetObjectTransformResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceCreateCameraLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FCreateCameraResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceDestroyCameraLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FDestroyCameraResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceSetResolutionLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FSetResolutionResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceCaptureNormalsLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FCaptureNormalsResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceCaptureOpticalFlowLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FCaptureOpticalFlowResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceSpawnObjectLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FSpawnObjectResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceDestroyObjectLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FDestroyObjectResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceSetMaterialLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FSetMaterialResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceListObjectsLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthListObjectsResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FListObjectsResponseLambda ResponseLambda;
};

UCLASS()
class UUESynthServiceSetLightingLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UUESynthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response);
public:
	FGrpcContextHandle Handle;
	UUESynthService::FSetLightingResponseLambda ResponseLambda;
};

