//Generated by TurboLink CodeGenerator, do not edit!
#include "UesynthService_Private.h"

void UUESynthServiceSetCameraTransformLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnSetCameraTransformResponse.RemoveDynamic(this, &UUESynthServiceSetCameraTransformLambdaWrapper::OnResponse);
}

void UUESynthServiceGetCameraTransformLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthGetCameraTransformResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetCameraTransformResponse.RemoveDynamic(this, &UUESynthServiceGetCameraTransformLambdaWrapper::OnResponse);
}

void UUESynthServiceCaptureRgbImageLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnCaptureRgbImageResponse.RemoveDynamic(this, &UUESynthServiceCaptureRgbImageLambdaWrapper::OnResponse);
}

void UUESynthServiceCaptureDepthMapLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnCaptureDepthMapResponse.RemoveDynamic(this, &UUESynthServiceCaptureDepthMapLambdaWrapper::OnResponse);
}

void UUESynthServiceCaptureSegmentationMaskLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnCaptureSegmentationMaskResponse.RemoveDynamic(this, &UUESynthServiceCaptureSegmentationMaskLambdaWrapper::OnResponse);
}

void UUESynthServiceSetObjectTransformLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnSetObjectTransformResponse.RemoveDynamic(this, &UUESynthServiceSetObjectTransformLambdaWrapper::OnResponse);
}

void UUESynthServiceGetObjectTransformLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthGetObjectTransformResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetObjectTransformResponse.RemoveDynamic(this, &UUESynthServiceGetObjectTransformLambdaWrapper::OnResponse);
}

void UUESynthServiceCreateCameraLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnCreateCameraResponse.RemoveDynamic(this, &UUESynthServiceCreateCameraLambdaWrapper::OnResponse);
}

void UUESynthServiceDestroyCameraLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnDestroyCameraResponse.RemoveDynamic(this, &UUESynthServiceDestroyCameraLambdaWrapper::OnResponse);
}

void UUESynthServiceSetResolutionLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnSetResolutionResponse.RemoveDynamic(this, &UUESynthServiceSetResolutionLambdaWrapper::OnResponse);
}

void UUESynthServiceCaptureNormalsLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnCaptureNormalsResponse.RemoveDynamic(this, &UUESynthServiceCaptureNormalsLambdaWrapper::OnResponse);
}

void UUESynthServiceCaptureOpticalFlowLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthImageResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnCaptureOpticalFlowResponse.RemoveDynamic(this, &UUESynthServiceCaptureOpticalFlowLambdaWrapper::OnResponse);
}

void UUESynthServiceSpawnObjectLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnSpawnObjectResponse.RemoveDynamic(this, &UUESynthServiceSpawnObjectLambdaWrapper::OnResponse);
}

void UUESynthServiceDestroyObjectLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnDestroyObjectResponse.RemoveDynamic(this, &UUESynthServiceDestroyObjectLambdaWrapper::OnResponse);
}

void UUESynthServiceSetMaterialLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnSetMaterialResponse.RemoveDynamic(this, &UUESynthServiceSetMaterialLambdaWrapper::OnResponse);
}

void UUESynthServiceListObjectsLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthListObjectsResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnListObjectsResponse.RemoveDynamic(this, &UUESynthServiceListObjectsLambdaWrapper::OnResponse);
}

void UUESynthServiceSetLightingLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcUesynthCommandResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnSetLightingResponse.RemoveDynamic(this, &UUESynthServiceSetLightingLambdaWrapper::OnResponse);
}

